df <- readRDS("data/raw/siconfi/raw_rgf.rds")
cat("Dimensoes:", nrow(df), "x", ncol(df), "\n")
cat("Colunas:", paste(names(df), collapse=", "), "\n\n")
cat("Amostra AC 2022:\n")
print(df[df$uf == "AC" & df$year == 2022, ])
cat("\nAmostra SP 2022:\n")
print(df[df$uf == "SP" & df$year == 2022, ])
cat("\nRaw RGF (AC 2022) — buscando resposta original...\n")
raw <- readRDS("data/raw/siconfi/raw_rgf.rds")
cat("Colunas:", paste(names(raw), collapse=", "), "\n")
